version: '3.7'

services:
  youtube:
    stop_grace_period: 1s
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6082:8080"
    environment:
      - PORT=8080
      - CREDENTIALS_PATH=/var/secrets/google/credentials.json
      - TOKEN_PATH=/var/secrets/google/token.json
    volumes:
      - ./secrets:/var/secrets/google
    secrets:
      - google-key

secrets:
  google-key:
    file: ./secrets/credentials.json
